[project]
name = 'Dream-Weaving-Collective'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.dream-architecture-builder]
path = 'contracts/dream-architecture-builder.clar'
clarity_version = 3
epoch = 'latest'

[contracts.lucid-dream-synchronizer]
path = 'contracts/lucid-dream-synchronizer.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
